name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unit-tests:
    runs-on:
      - self-hosted
      - linux
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: python -m pip install --upgrade pip poetry

      - name: Install dependencies
        run: poetry install --with dev --no-interaction --no-root

      - name: Syntax check
        run: poetry run python -m compileall src tests

      - name: Run tests
        run: poetry run pytest -v
